<?php
/**
 * Make the studio's own typefaces available on the brief page.
 *
 * Why this exists: on moreatelier.com.au the @font-face rules for these two
 * faces are generated by Elementor into PER-PAGE stylesheets. Bradford happens
 * to sit in the global kit (post-7.css) so it is everywhere, but Acumin is
 * declared in a different post-NNNN.css on every page — homepage 9365, contact
 * 6355, portfolio 6920. A brand-new page that doesn't use Acumin in an Elementor
 * widget would therefore never load it, and the brief would quietly fall back to
 * Arial.
 *
 * So we declare both ourselves, pointing at the files already sitting in the
 * media library. Nothing is copied or redistributed — it is the site's own
 * licensed copy, served from the site's own uploads folder.
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

/** The faces the brief asks for, in the order the CSS names them. */
function madb_font_families() {
	return array( 'BradfordLLTT-Light', 'AcuminPro-Light' );
}

/**
 * Locate a face in the uploads folder. Elementor's custom-font uploads land in
 * the usual year/month folders, so look there rather than assuming one path.
 *
 * @return array ext => absolute path
 */
function madb_find_font_files( $basedir, $family ) {
	$found = array();
	$patterns = array(
		$basedir . '/*/*/' . $family . '.*',   // uploads/2025/11/Name.woff2
		$basedir . '/*/' . $family . '.*',
		$basedir . '/' . $family . '.*',
		$basedir . '/elementor/custom-fonts/' . $family . '.*',
	);
	foreach ( $patterns as $pattern ) {
		foreach ( (array) glob( $pattern ) as $path ) {
			$ext = strtolower( pathinfo( $path, PATHINFO_EXTENSION ) );
			if ( in_array( $ext, array( 'woff2', 'woff', 'ttf', 'otf' ), true ) && ! isset( $found[ $ext ] ) ) {
				$found[ $ext ] = $path;
			}
		}
		if ( $found ) { break; }
	}
	return $found;
}

/**
 * @font-face CSS for whatever we can actually find. Returns '' if the files
 * aren't there, in which case the stacks in brief.css fall back on their own.
 */
function madb_font_face_css() {
	$cached = get_transient( 'madb_font_css' );
	if ( false !== $cached ) { return $cached; }

	$up  = wp_upload_dir();
	$css = '';

	foreach ( madb_font_families() as $family ) {
		$files = madb_find_font_files( $up['basedir'], $family );
		if ( ! $files ) { continue; }

		$srcs = array();
		foreach ( array( 'woff2' => 'woff2', 'woff' => 'woff', 'ttf' => 'truetype', 'otf' => 'opentype' ) as $ext => $fmt ) {
			if ( empty( $files[ $ext ] ) ) { continue; }
			$url = str_replace( $up['basedir'], $up['baseurl'], $files[ $ext ] );
			$srcs[] = sprintf( 'url("%s") format("%s")', esc_url( $url ), $fmt );
		}
		if ( ! $srcs ) { continue; }

		// A single-weight file covering the whole range, so asking for 300 or
		// 400 resolves to this file instead of the browser faking a weight.
		$css .= sprintf(
			"@font-face{font-family:'%s';src:%s;font-weight:100 900;font-style:normal;font-display:swap;}\n",
			$family,
			implode( ',', $srcs )
		);
	}

	// Cache a hit for a day, but a MISS for only a few minutes: if the fonts are
	// uploaded after the plugin is installed, a day-long empty cache would leave
	// the brief in a fallback face and look like a bug.
	set_transient( 'madb_font_css', $css, $css ? DAY_IN_SECONDS : 5 * MINUTE_IN_SECONDS );
	return $css;
}

/** Clear the cache when the media library changes. */
add_action( 'add_attachment', function () { delete_transient( 'madb_font_css' ); } );
add_action( 'delete_attachment', function () { delete_transient( 'madb_font_css' ); } );

/** Admin notice if the faces can't be found, so it isn't a silent downgrade. */
add_action( 'admin_notices', function () {
	$screen = get_current_screen();
	if ( ! $screen || 'settings_page_madb' !== $screen->id ) { return; }

	$up = wp_upload_dir();
	$missing = array();
	foreach ( madb_font_families() as $family ) {
		if ( ! madb_find_font_files( $up['basedir'], $family ) ) { $missing[] = $family; }
	}
	if ( ! $missing ) {
		echo '<div class="notice notice-success"><p>Both studio typefaces were found in your media library and the brief will use them.</p></div>';
		return;
	}
	printf(
		'<div class="notice notice-warning"><p>Could not find %s in the media library, so the brief will fall back to a substitute for %s. Upload the font file(s) to Media and reload this page.</p></div>',
		esc_html( implode( ' and ', $missing ) ),
		count( $missing ) > 1 ? 'both' : 'that one'
	);
} );
